version: '2'
services:
  gator-app:
    image: gator
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://gator-mariadb:3306/gator
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://gator-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gator-elasticsearch:9200
    ports:
      - 8080:8080
  gator-mariadb:
    extends:
      file: mariadb.yml
      service: gator-mariadb
  gator-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gator-elasticsearch
