version: '2'
services:
  gator-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    volumes:
         - ~/volumes/gator/elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
      - 'use_tls=no'
